apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration 
metadata:
  name: assign-class-label-webhook
webhooks:
- name: assign-class-label-webhook.nerc.com
  clientConfig: 
    service:
      namespace: ope-test
      name: assign-class-label-webhook
      path: /mutate
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVPekNDQXlPZ0F3SUJBZ0lVVWpJdWw5NjRmMW9pR1h1REpOaGJJN1pra2VFd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2daRXhDekFKQmdOVkJBWVRBbFZUTVJZd0ZBWURWUVFJREExTllYTnpZV05vZFhObGRIUnpNUTh3RFFZRApWUVFIREFaQ2IzTjBiMjR4RURBT0JnTlZCQW9NQjFKbFpDQklZWFF4RVRBUEJnTlZCQXNNQ0ZKbGMyVmhjbU5vCk1SQXdEZ1lEVlFRRERBZDNaV0pvYjI5ck1TSXdJQVlKS29aSWh2Y05BUWtCRmhOcGMzUmhjR3hsZEVCeVpXUm8KWVhRdVkyOXRNQjRYRFRJME1EZ3dNakU0TURJME1Wb1hEVEkzTURVeU16RTRNREkwTVZvd2daRXhDekFKQmdOVgpCQVlUQWxWVE1SWXdGQVlEVlFRSURBMU5ZWE56WVdOb2RYTmxkSFJ6TVE4d0RRWURWUVFIREFaQ2IzTjBiMjR4CkVEQU9CZ05WQkFvTUIxSmxaQ0JJWVhReEVUQVBCZ05WQkFzTUNGSmxjMlZoY21Ob01SQXdEZ1lEVlFRRERBZDMKWldKb2IyOXJNU0l3SUFZSktvWklodmNOQVFrQkZoTnBjM1JoY0d4bGRFQnlaV1JvWVhRdVkyOXRNSUlCSWpBTgpCZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF0QldWMUIxdWhrZ29BTVEzcnVvMWw0L2lPUDc3CnZBYVJvbi8wSVBja20wUVhaVm4xNzRvcDFWSkdCbFZRVDhNeVl2bTZ1Y1FRT01HWkMvOEFCS2FkNXk3TlVKOGoKYzV5aVR2RTBzVytLWWtxcnUyTTR2aE5nblJMc0tXZjhVN1ZxZ0ZsTS80N1NIcENkTGhpZlZUWkV2MkdwOGFEVgpyUFNkbEdTa0hETWZxK3JiZW9PZHZ4QStxTDNwWFp5aThQcElYLzN1VHQ2b0dORnRueGY1cFJsMUpjeEJZRkdJCnp0N3cwTXBOVlBEVllLVzZUQ0JIRG5DWDFHeFo0d1FjazJtM0hlZ1lxTERqcTIxK2RYaDlaNDVPYm5KN0kza0YKOHpSWmhPMEJFd3NNdzBnMFgxcXZ3WUh5TlJiOFVFTlBGZDlxanlUT3FDck84RkRNNENxdUo2Z0R5UUlEQVFBQgpvNEdJTUlHRk1CMEdBMVVkRGdRV0JCUXFwM1JWTHVNV2g0N3UzUU1Pa20zKzdmc21DakFmQmdOVkhTTUVHREFXCmdCUXFwM1JWTHVNV2g0N3UzUU1Pa20zKzdmc21DakFQQmdOVkhSTUJBZjhFQlRBREFRSC9NRElHQTFVZEVRUXIKTUNtQ0oyRnpjMmxuYmkxamJHRnpjeTFzWVdKbGJDMTNaV0pvYjI5ckxtOXdaUzEwWlhOMExuTjJZekFOQmdrcQpoa2lHOXcwQkFRc0ZBQU9DQVFFQUVsV1MrWU52VkdmVjNibUFNQTNxRUNYNU9XZ0pjYVdrU0M1ck9UWm9kaWp2Ckt4UVlaQW80ME1aMlRRdjlabGE2VmU3czBOekVaY1lNc3RvRWFHbHNTQ2xETnBTZWlGQ1VsNjF1OVEvN2VBc0oKdDd4dzg0Qk1tem1pQ2dPMmt1alhyUmV3ckpBQlArTVVkdHkyR3FEdk53a3VVM3BNc0tobkNGelNqeVZoTXRZZwoxd2ovc1VscDhjejZxN0ZKMUlIZWpWQ0tyUWxvUXgzOStLcmR3N1p3NHpPUHBnWmNGUG14TklFZGxRUmtXSDlJCmJPcEZqazdXQ0k3b1JCdG92R0JMenVGM3FITmhYaDF5eSs3UWJHZlZ4U2RBTmVGdEdOS3BHNW1wb2lLMUZoYWgKL0N5YVNZck1obHUxcFJLdGZNK25ud3ljN3NnWm0zUVZYOVNxanZMOER3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  rules:
    - operations: ["CREATE"]
      apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values:
          - ope-test
  sideEffects: None
  admissionReviewVersions: ["v1"] 
  
